name:  Test Menu Pages Cheerio

on:
  schedule:
    - cron: '0 * * * *' # Executes every hour

  workflow_dispatch:

jobs:
  test_menus:
    name: test_menus
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cheerio

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
          cache: 'yarn'
          cache-dependency-path: 'cheerio/yarn.lock'

      - name: Install Dependencies
        run: yarn install

      - name: Run menu scraping for zld
        env:
          ZLD_PURGE_CACHE_WEBHOOK: ${{ secrets.ZLD_PURGE_CACHE_WEBHOOK }}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        run: node zld/menu.js

      - name: Run menu scraping for muv
        env:
          MUV_PURGE_CACHE_WEBHOOK: ${{ secrets.MUV_PURGE_CACHE_WEBHOOK }}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        run: node muv/menu.js
